//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuegoBox.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public double TotalAmount { get; set; }
        public System.Guid DeliveryAddressID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.Guid StatusID { get; set; }
        public string isCancelled { get; set; }
    
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual User User { get; set; }
        public virtual Status Status { get; set; }
    }
}
