//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FuegoBox.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariantPropertyValue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VariantPropertyValue()
        {
            this.VariantProperties = new HashSet<VariantProperty>();
        }
    
        public System.Guid ID { get; set; }
        public System.Guid PropertyID { get; set; }
        public System.Guid ValueID { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual Value Value { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VariantProperty> VariantProperties { get; set; }
    }
}
